name: Check Pull Request
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test
        run: |
          files=$(ls .github/workflows)
          echo "We have these files: $files"