name: Check Pull Request
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge with target branch
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}
          git fetch origin
          git merge origin/${{ github.base_ref }} --no-ff --no-squash --no-edit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Test
        uses: docker/build-push-action@v6
        with:
          target: test

      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: ${{ github.repository }}:latest