name: Check Pull Request
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-pull-request:
    # no need to merge the branch if triggered by the pull request branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Test
        uses: docker/build-push-action@v6
        with:
          target: test

      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: ${{ github.repository }}:latest